# CONFIGURAÇÃO DE PORTA
server.port=8085

# NOME DO SEU PROJETO
spring.application.name=controleestoque

# CONFIGURAÇÃO DO BANCO DE DADOS (Sem senha)
spring.datasource.url=jdbc:mysql://localhost:3306/estoque_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURAÇÕES DO HIBERNATE / JPA 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false